version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    networks:
      - rabbitmq_network
    ports:
      - "5672:5672"
      - "15672:15672"

networks:
  rabbitmq_network:
    driver: bridge